### ISSUE TITLE
skip-github-pull-request option set to true will cause no release being created.

### ISSUE THREAD

**Issue by liulirun** [liulirun/googleapi-please-release#11]
From the [README](https://github.com/googleapis/release-please-action?tab=readme-ov-file#action-inputs), skip-github-pull-request should only affect if a release PR being created , should not affect if a release being created. -- please correct me if I were wrong. 

I tried below set up like this. 
```
on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

name: release

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: googleapis/release-please-action@v4
        with:
          token: ${{ secrets.GH_TOKEN }}
          skip-github-pull-request: true
          release-type: simple
```
and full workflow logs 
```
Running release-please version: 16.18.0
✔ Looking for latest release on branch: main with prefix: 
❯ Fetching merge commits on branch main with cursor: undefined
❯ Found latest release pull request: 9 version: 1.2.0
❯ Fetching releases with cursor undefined
❯ found release for  Version {
  major: 1,
  minor: 2,
  patch: 0,
  preRelease: undefined,
  build: undefined
}
❯ found release for  Version {
  major: 1,
  minor: 1,
  patch: 1,
  preRelease: undefined,
  build: undefined
}
❯ SHA not found in recent commits to branch main, skipping
❯ found release for  Version {
  major: 1,
  minor: 1,
  patch: 0,
  preRelease: undefined,
  build: undefined
}
❯ SHA not found in recent commits to branch main, skipping
❯ found release for  Version {
  major: 1,
  minor: 0,
  patch: 0,
  preRelease: undefined,
  build: undefined
}
❯ SHA not found in recent commits to branch main, skipping
❯ found 2 possible releases. [
  Version {
    major: 1,
    minor: 2,
    patch: 0,
    preRelease: undefined,
    build: undefined
  },
  Version {
    major: 1,
    minor: 2,
    patch: 0,
    preRelease: undefined,
    build: undefined
  }
]
✔ Building releases
✔ Building strategies by path
❯ .: simple
```

function `buildReleases()` not being called at all, as shown in the logs. 

My understanding is a release should be created unless I set `skip-github-release: true` to override the default value
